quarkus:
  index-dependency:
    # needed for rest-client-jakarta
    pnc:
      group-id: org.jboss.pnc

  oidc:
    client-id: client

  oidc-client:
    auth-server-url: https://keycloak/auth
    client-id: quarkus_app
    credentials:
      secret: secret
    refresh-token-time-skew: 2M

  container-image:
    registry: quay.io
    group: rh-newcastle-devel
    name: attester
    additional-tags:
    - latest

mp:
  messaging:
    incoming:
      logs:
        connector: smallrye-kafka
        topic: logs
        auto:
          offset:
            reset: earliest

attester:
  cosign:
    privateKeyPath: /home/dcheung/slsa/cosign.key
    publicKeyPath: /home/dcheung/slsa/cosign.pub
    privateKeyPassword: dustin
  orchUrl: https://localhost
  container-registry:
    username: user
    password: password
    image: quay.io/dcheung/pnc-test
  addBuildAttribute: true
  # whether to attest from messages received in Kafka of successful builds
  kafkaListenerAttest: false
  publicKey:
    ociImageRegistry: quay.io/dcheung/public-key
    ociSha256: 1234

pnc_client_auth:
  type: OIDC # or LDAP
  ldap_credentials:
    path: /mnt/secrets/ldap_credentials # file must be in format: <username>:<password>
