package org.jboss.pnc.attester.utils.wrapper;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import org.jboss.pnc.attester.utils.configuration.AttesterConfig;

/**
 * A wrapper around the Cosign CLI for signing blobs with a Cosign private key.
 * <br/>
 * Relies on COSIGN_PASSWORD to decrypt the key if encrypted.
 * Once https://github.com/sigstore/sigstore-java will be able to handle Cosign-generated private keys
 * ("-----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----"), we might replace this wrapper with proper java code.
 * <br/>
 * Bouncycastle is also not good because it does not recognize them as PKCS#8 PEM keys.
 * <br/>
 * Author: Andrea Vibelli avibelli@redhat.com via the sentinel repository
 */
@ApplicationScoped
public class CosignWrapper {

    @Inject
    AttesterConfig config;

    /**
     * Attest a container image name with the predicate generated by PNC
     */
    public void attestPredicate(
            Path predicate,
            String imageNameTag) throws IOException, InterruptedException {

        List<String> commands = List.of(
                "cosign",
                "attest",
                "--registry-username",
                config.getContainerRegistryUsername(),
                "--registry-password",
                config.getContainerRegistryPassword(),
                "--predicate",
                predicate.toString(),
                "--key",
                config.getCosignPrivateKeyPath().toString(),
                "--type",
                "slsaprovenance1",
                imageNameTag);

        ProcessBuilder pb = new ProcessBuilder(commands);
        String password = config.getCosignPrivateKeyPassword();
        pb.environment().put("COSIGN_PASSWORD", password != null ? password : "");

        Process p = pb.start();

        // Drain stdout/stderr in separate threads to avoid blocking
        StreamGobbler outGobbler = new StreamGobbler(p.getInputStream(), "cosign-out");
        StreamGobbler errGobbler = new StreamGobbler(p.getErrorStream(), "cosign-err");
        outGobbler.start();
        errGobbler.start();

        // 1. Wait for process to finish
        int exitCode = p.waitFor();

        if (exitCode != 0) {
            String err = Files.readString(errGobbler.capturedFile);
            throw new RuntimeException("cosign failed: " + err);
        }
    }

    /**
     * Verifies an attestation
     *
     * @return true if verification succeeds, false otherwise
     */
    public boolean verifyAttestation(String imageNameTag)
            throws IOException, InterruptedException {

        List<String> commands = List.of(
                "cosign",
                "verify-attestation",
                "--key",
                config.getCosignPublicKeyPath().toString(),
                "--type",
                "slsaprovenance1",
                imageNameTag);

        ProcessBuilder pb = new ProcessBuilder(commands);
        Process p = pb.start();

        StreamGobbler outGobbler = new StreamGobbler(p.getInputStream(), "cosign-out");
        StreamGobbler errGobbler = new StreamGobbler(p.getErrorStream(), "cosign-err");
        outGobbler.start();
        errGobbler.start();

        int exitCode = p.waitFor();
        return exitCode == 0;
    }
}